name: INITIALIZE

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download NGROK & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/wrcftnozz/tsest/main/Files/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/wrcftnozz/tsest/main/Files/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & NGROK to Windows Directory
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Authorize NGROK
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download files
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/wrcftnozz/tsest/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/wrcftnozz/tsest/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/wrcftnozz/tsest/main/Files/loop.bat -OutFile loop.bat
    - name: Generate YML file for NGROK
      run: start NGROK-US.bat
    - name: Enable access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create tunnel
      run: sc start ngrok
    - name: Connection instructions
      run: cmd /c NGROK-CHECK.bat
    - name: Complete (checking status)
      run: cmd /c loop.bat 

